import fs from 'node:fs';
import path from 'node:path';
import type { DecisionTrace } from '../state/DecisionTraceStore.js';
import type { AuditLogEntry } from '../types.js';
import { oneLine } from './renderUtils.js';

/**
 * Inputs for a story handoff document. Every field comes from a DURABLE source
 * (git log, the decision_traces table, the audit_log table, the persisted
 * log_tail) so the doc can be assembled even after a hard crash that killed the
 * worker mid-flight — not just a graceful timeout.
 */
export interface HandoffInputs {
  storyId: string;
  epicId: string;
  title: string;
  description?: string;
  branchName: string;
  worktreePath: string;
  /** Current agent status (failed / blocked / done / ...). */
  status: string;
  /** Last worker-result summary, when available. */
  summary?: string;
  acceptanceCriteria: string[];
  /** Commits on the story branch since it diverged, oldest first. */
  commits: Array<{ sha: string; subject: string }>;
  /** Overall `git diff --stat` summary line for the branch, if any. */
  diffStat?: string;
  /** Whether the worktree still has uncommitted changes. */
  dirty?: boolean;
  /** Chronological reasoning timeline for the story (claude backend only). */
  traces: DecisionTrace[];
  /** Recent audit rows for the agent (most recent first). */
  audit: AuditLogEntry[];
  /** Tail of the worker's output. */
  logTail?: string;
  /** ISO timestamp the doc was generated. Defaults to now. */
  generatedAt?: string;
}

/** How many trace / audit / commit rows to surface (keeps the doc compact). */
const MAX_TRACES = 12;
const MAX_AUDIT = 10;
const MAX_COMMITS = 30;

/**
 * Assembles and materializes a per-story handoff document so a fresh worker (or
 * a human) can resume after a failure of any kind. The default `telemetry` mode
 * is a pure render over already-persisted state — zero extra LLM tokens. The
 * document shape mirrors the team's `/handoff` skill (Goal / Current state /
 * Key decisions / Artifacts / Next steps / Suggested skills) but is produced
 * automatically by loom, and references artifacts by path rather than copying
 * them.
 */
export class StoryHandoff {
  /** Path where a story's handoff doc is materialized (sibling of guidance/). */
  static pathFor(projectRoot: string, storyId: string): string {
    return path.join(projectRoot, '.loom', 'handoff', `${storyId}.md`);
  }

  /** Reads the materialized handoff doc, or null when none exists. */
  static read(projectRoot: string, storyId: string): string | null {
    try {
      return fs.readFileSync(StoryHandoff.pathFor(projectRoot, storyId), 'utf8');
    } catch {
      return null;
    }
  }

  /** Writes the handoff doc to disk, creating `.loom/handoff/` as needed. */
  static write(projectRoot: string, storyId: string, content: string): string {
    const file = StoryHandoff.pathFor(projectRoot, storyId);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content, 'utf8');
    return file;
  }

  /**
   * Pure telemetry render — markdown from durable sources, no LLM. This is the
   * default and the recommended mode (`policy.agents.handoff: telemetry`).
   */
  static render(inputs: HandoffInputs): string {
    const generatedAt = inputs.generatedAt ?? new Date().toISOString();
    const lines: string[] = [];

    lines.push(`# Handoff — ${inputs.storyId}`);
    lines.push('');
    lines.push(`Generated: ${generatedAt}`);
    lines.push(`Status: ${inputs.status}`);
    lines.push('');
    lines.push(
      '> Auto-generated by loom from durable telemetry (git log + decision ' +
        'traces + audit). A fresh worker resuming this story should CONTINUE ' +
        'from the commits below — do not start over.'
    );

    // ── Goal ────────────────────────────────────────────────────────────────
    lines.push('');
    lines.push('## Goal');
    lines.push(`**${inputs.title}** (epic ${inputs.epicId})`);
    if (inputs.description && inputs.description.trim()) {
      lines.push('');
      lines.push(inputs.description.trim());
    }
    if (inputs.acceptanceCriteria.length > 0) {
      lines.push('');
      lines.push('Acceptance criteria:');
      for (const ac of inputs.acceptanceCriteria) lines.push(`- [ ] ${ac}`);
    }

    // ── Current state ─────────────────────────────────────────────────────────
    lines.push('');
    lines.push('## Current state');
    if (inputs.summary && inputs.summary.trim()) {
      lines.push(`Last outcome: ${inputs.summary.trim()}`);
      lines.push('');
    }
    if (inputs.commits.length > 0) {
      lines.push(`Committed work on \`${inputs.branchName}\` (${inputs.commits.length} commit(s)):`);
      const shown = inputs.commits.slice(-MAX_COMMITS);
      for (const c of shown) lines.push(`- \`${c.sha}\` ${c.subject}`);
      if (inputs.commits.length > shown.length) {
        lines.push(`- … and ${inputs.commits.length - shown.length} earlier commit(s)`);
      }
    } else {
      lines.push('No commits yet on the story branch.');
    }
    if (inputs.diffStat && inputs.diffStat.trim()) {
      lines.push('');
      lines.push('Diffstat vs. branch base:');
      lines.push('```');
      lines.push(inputs.diffStat.trim());
      lines.push('```');
    }
    if (inputs.dirty) {
      lines.push('');
      lines.push(
        '> NOTE: the worktree had uncommitted changes at handoff time. loom ' +
          'checkpoints these as a `wip: … [loom]` commit on timeout/budget kills.'
      );
    }

    // ── Key decisions ────────────────────────────────────────────────────────
    const decisionTraces = inputs.traces.filter(
      (t) => t.kind === 'tool_intent' || t.kind === 'pivot' || t.kind === 'plan_rationale'
    );
    if (decisionTraces.length > 0) {
      lines.push('');
      lines.push('## Key decisions (from the reasoning trace)');
      const shown = decisionTraces.slice(-MAX_TRACES);
      for (const t of shown) {
        const subject = t.subject ? `\`${t.subject}\` — ` : '';
        lines.push(`- ${subject}${oneLine(t.rationale, 200)}`);
      }
    }

    // ── Artifacts (reference only) ───────────────────────────────────────────
    lines.push('');
    lines.push('## Artifacts (reference only)');
    lines.push('| Kind | Location |');
    lines.push('| --- | --- |');
    lines.push(`| Branch | \`${inputs.branchName}\` |`);
    lines.push(`| Worktree | \`${inputs.worktreePath}\` |`);
    lines.push(`| Handoff doc | \`.loom/handoff/${inputs.storyId}.md\` |`);

    // ── Recent activity (audit) ──────────────────────────────────────────────
    if (inputs.audit.length > 0) {
      lines.push('');
      lines.push('## Recent activity');
      const shown = inputs.audit.slice(0, MAX_AUDIT);
      for (const a of shown) {
        lines.push(`- ${a.timestamp} — ${a.action}${a.command ? ` (${a.command})` : ''}`);
      }
    }

    // ── Next steps ───────────────────────────────────────────────────────────
    lines.push('');
    lines.push('## Next steps');
    lines.push('1. Review the commits above — they are your starting point; do not redo them.');
    lines.push('2. Re-read the acceptance criteria and finish whatever is unchecked.');
    lines.push('3. Run the targeted tests for the service(s) you touched, then commit.');

    // ── Log tail ─────────────────────────────────────────────────────────────
    if (inputs.logTail && inputs.logTail.trim()) {
      lines.push('');
      lines.push('## Last worker output (tail)');
      lines.push('```');
      lines.push(inputs.logTail.trim());
      lines.push('```');
    }

    return lines.join('\n') + '\n';
  }
}
