import yaml from 'js-yaml';
import type { EpicYaml } from '../types.js';

const BASE_HEADER = '# Generated by loom — PM persona (John), enriched by Architect (Winston)';

/**
 * Serializes an epic to YAML with loom's canonical dump options. Centralized so
 * the planning agents that rewrite epic files (Architect, QA) share one set of
 * options — change `lineWidth`/`noRefs`/etc. here and every writer follows.
 *
 * `enrichedBy` is appended to the provenance header comment (e.g. 'and QA
 * (Tessa)') to record who last touched the file; omit it for the base case.
 */
export function serializeEpic(epic: EpicYaml, enrichedBy?: string): string {
  const header =
    BASE_HEADER +
    (enrichedBy ? ` ${enrichedBy}` : '') +
    '\n# Validated against schemas/epic.schema.yaml\n';
  return header + yaml.dump(epic, { lineWidth: 100, noRefs: true });
}
